MStokluska/integreatly-operator

- manifests/integreatly-cloud-resources/0.24.1/cloud-resource-operator.clusterserviceversion.yaml
- manifests/integreatly-grafana/3.10.1/grafana-operator.v3.10.1.clusterserviceversion.yaml
- manifests/integreatly-marin3r/0.7.0/marin3r.v0.7.0.clusterserviceversion.yaml
- manifests/integreatly-monitoring/1.6.0/application-monitoring-operator.v1.6.0.clusterserviceversion.yaml
- manifests/integreatly-rhsso/13.0.1/keycloak-operator.v13.0.1.clusterserviceversion.yaml
> mock 2.0.0

- manifests/integreatly-cloud-resources/0.24.1/cloud-resource-operator.clusterserviceversion.yaml
- manifests/integreatly-grafana/3.10.1/grafana-operator.v3.10.1.clusterserviceversion.yaml
- manifests/integreatly-marin3r/0.7.0/marin3r.v0.7.0.clusterserviceversion.yaml
- manifests/integreatly-monitoring/1.6.0/application-monitoring-operator.v1.6.0.clusterserviceversion.yaml
- manifests/integreatly-rhsso/13.0.1/keycloak-operator.v13.0.1.clusterserviceversion.yaml
> mock v2.1.0

- manifests/integreatly-cloud-resources/0.24.1/cloud-resource-operator.clusterserviceversion.yaml
- manifests/integreatly-grafana/3.10.1/grafana-operator.v3.10.1.clusterserviceversion.yaml
- manifests/integreatly-marin3r/0.7.0/marin3r.v0.7.0.clusterserviceversion.yaml
- manifests/integreatly-monitoring/1.6.0/application-monitoring-operator.v1.6.0.clusterserviceversion.yaml
- manifests/integreatly-rhsso/13.0.1/keycloak-operator.v13.0.1.clusterserviceversion.yaml
> mock components images

- manifests/integreatly-cloud-resources/0.24.1/cloud-resource-operator.clusterserviceversion.yaml
- manifests/integreatly-grafana/3.10.1/grafana-operator.v3.10.1.clusterserviceversion.yaml
- manifests/integreatly-marin3r/0.7.0/marin3r.v0.7.0.clusterserviceversion.yaml
- manifests/integreatly-monitoring/1.6.0/application-monitoring-operator.v1.6.0.clusterserviceversion.yaml
- manifests/integreatly-rhsso/13.0.1/keycloak-operator.v13.0.1.clusterserviceversion.yaml
> mock 2.6.0

- test-cases/tests/alerts/c18-validate-api-usage-alerts.md
- test-cases/tests/alerts/rate-limit.js
based on discussion in https://issues.redhat.com/browse/MGDAPI-2214
> test: update c18 test case and script

- products/installation-cpaas.yaml
> MGDAPI-3412 0.8.0

- products/installation-cpaas.yaml
> MGDAPI-3412 dummy pr to re-trigger msp

- .codecov.yml
- config/scorecard/kuttl/01-happy-path/00-test-pod-template.yaml
> Scorecards fix

- config/scorecard/kustomization.yaml
- products/installation-cpaas.yaml
> MGDAPI-3412 test3

- config/scorecard/kuttl/01-happy-path/00-test-pod-template.yaml
- config/scorecard/kuttl/02-scalability/00-test-pod-template.yaml
> MGDAPI-3412 test6

- products/installation-cpaas.yaml
> MGDAPI-3412 create 0.8.0 image

- README.md
> MGDAPI-3412 test8

- config/scorecard/kuttl/00-installation/01-create-secrets.yaml
- config/scorecard/kuttl/00-installation/02-cluster-storage.yaml
> MGDAPI-3412 update test config

- bundles/managed-api-service/1.22.0/manifests/managed-api-service.clusterserviceversion.yaml
- config/rbac/role.yaml
> MGDAPI-3412 add 3scale rbac

- README.md
> MGDAPI-3412 retrigger cpaas

- config/rbac/role.yaml
> MGDAPI-3412 remove quotes

- products/installation-cpaas.yaml
> MGDAPI-3412 test17

- products/installation-cpaas.yaml
Reverts MStokluska/integreatly-operator#121
> Revert "MGDAPI-3412 test17"

- config/scorecard/kuttl/01-happy-path/00-test-pod-template.yaml
> MGDAPI-3412 remove some tests

- products/installation-cpaas.yaml
> MGDAPI-3412 bump 3scale to second 0.8.0 bundle

- products/installation-cpaas.yaml
> MGDAPI-3412 bump 3scale-test19

- version/version.go
> bump to mock version

- bundles/managed-api-service/1.24.0/manifests/managed-api-service.clusterserviceversion.yaml
- version/version.go
> trigger update to bundle

- version/version.go
> rhoam 1.71.0 mock
